[package]
name = "png_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "png_reader"
crate-type = ["lib"]

[dependencies]
compress = "0.2.1"
rayon = "1.9.0"
png = "0.17.13"